[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "NIDRA"
version = "0.1.0"
authors = [
  { name="Paul Zerr", email="zerr.paul@gmail.com" },
]
description = "A tool for scoring sleep data from PSG and forehead EEG recordings."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "scipy",
    "mne",
    "seaborn",
    "pandas",
    "onnxruntime",
    "dearpygui",
    "matplotlib",
]

[project.urls]
"Homepage" = "https://github.com/p-zerr/NIDRA"

[project.scripts]
nidra-gui = "NIDRA.gui:launch_gui"
nidra = "NIDRA.cli:run_cli"

[tool.setuptools]
packages = ["NIDRA"]